FROM python:3.7-alpine

RUN apk add --no-cache wkhtmltopdf

# for pillow
RUN apk add build-base python-dev py-pip jpeg-dev zlib-dev
ENV LIBRARY_PATH=/lib:/usr/lib

# todo: requirements
COPY ./ /
RUN pip install -r /hw_2_qrcode_bot/s2_qrcode_img_generator/requirements.txt

ENV PYTHONPATH "${PYTHONPATH}:${PWD}"
CMD ["python", "hw_2_qrcode_bot/s2_qrcode_img_generator/app.py"]
