FROM python:3.7-alpine

COPY ./ /
RUN pip install -r /hw_2_qrcode_bot/s4_coupon_vk_bot/requirements.txt

ENV PYTHONPATH "${PYTHONPATH}:${PWD}"
CMD ["python", "hw_2_qrcode_bot/s4_coupon_vk_bot/app.py"]
