version: '3.7'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
